UPDATE SALESMAN SET GRADE=200 WHERE SALESMAN_CITY = 'Rome';
UPDATE SALESMAN SET GRADE=300 WHERE SALESMAN_NAME = 'James Hoog';
UPDATE SALESMAN SET SALESMAN_NAME= 'Pierre' WHERE SALESMAN_NAME='McLyon';
SELECT * FROM SALESMAN;