INSERT INTO SALESMAN VALUES( 5001,'James Hoog','New York',15);
INSERT INTO SALESMAN VALUES( 5002, 'Nail Knite', 'Paris', 13);
INSERT INTO SALESMAN VALUES( 5005, 'PIT ALEX', 'LONDON', 11);
INSERT INTO SALESMAN VALUES( 5006, 'McLyon', 'Paris', 14);
INSERT INTO SALESMAN VALUES( 5007, 'Paul Adam', 'Rome', 13);
INSERT INTO SALESMAN VALUES( 5003, 'Lauson Hen', 'Sane Jose', 12);


SELECT * FROM SALESMAN;
